# Generated by Django 3.0.4 on 2020-03-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20200307_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bid_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
