# Generated by Django 3.0.4 on 2020-03-08 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_highest_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='Used', max_length=4),
        ),
        migrations.AddField(
            model_name='auction',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time created'),
        ),
    ]
